In [1]:
import numpy as np
import pandas as pd
from scipy.spatial import procrustes

In [4]:
# get location matrices

path = './dataFolder/procrustes/'

before = pd.read_csv(path + 'Results_beforeRotation.csv')
matrix_1 = before.loc[:,'X':'Y']
after = pd.read_csv(path + 'Results_after15Rotation.csv')
matrix_2 = after.loc[:, 'X':'Y']

In [6]:
mtx1, mtx2, disparity = procrustes(matrix_1, matrix_2)

In [11]:
mtx1

array([[-0.31437322, -0.30448482],
       [-0.00586574, -0.31378843],
       [-0.00363287, -0.00490879],
       [ 0.00430645,  0.31339874],
       [ 0.33278543,  0.30471513],
       [-0.3192111 ,  0.32853235],
       [ 0.30599105, -0.32346417]])

In [8]:
mtx2

array([[-0.31377537, -0.30683352],
       [-0.00325904, -0.31724066],
       [-0.00260121,  0.00162006],
       [ 0.00412631,  0.31426031],
       [ 0.33156043,  0.30518214],
       [-0.31746657,  0.32796671],
       [ 0.30141546, -0.32495504]])

In [9]:
disparity

9.729224902253031e-05

In [19]:
matrix_1_inv = np.linalg.inv(matrix_1.values.T[:,0:2])

In [23]:
A = mtx1.T*matrix_1_inv

ValueError: operands could not be broadcast together with shapes (2,7) (2,2) 

In [21]:
mtx1

array([[-0.31437322, -0.30448482],
       [-0.00586574, -0.31378843],
       [-0.00363287, -0.00490879],
       [ 0.00430645,  0.31339874],
       [ 0.33278543,  0.30471513],
       [-0.3192111 ,  0.32853235],
       [ 0.30599105, -0.32346417]])